import type { BlogPost } from "@/lib/blog-types";

export const sampleBlogPost: BlogPost = {
  id: "blog-complete-eyewear-guide",
  slug: "how-to-choose-perfect-eyeglasses",
  title: "How to Choose the Perfect Eyeglasses for Your Face and Lifestyle",
  excerpt:
    "A practical optician-led guide to frame shape, measurements, materials and lenses so your next pair looks balanced and feels comfortable all day.",
  category: "Frame guide",
  coverImage: "/about-man.jpg",
  coverAlt: "Man wearing well-fitted black optical eyeglasses",
  author: "Nigah Editorial",
  status: "published",
  featured: true,
  seoTitle: "How to Choose Perfect Eyeglasses: Expert Frame Guide",
  seoDescription:
    "Learn how to choose eyeglasses for your face shape, frame size, lifestyle and prescription with practical advice from Nigah opticians.",
  keywords: [
    "how to choose eyeglasses",
    "best frames for face shape",
    "eyeglasses size guide",
    "optical frames Pakistan",
    "comfortable glasses",
  ],
  createdAt: "2026-09-23T10:00:00.000Z",
  updatedAt: "2026-09-23T10:00:00.000Z",
  publishedAt: "2026-09-23T10:00:00.000Z",
  blocks: [
    {
      id: "sample-intro",
      type: "paragraph",
      text: "The best eyeglasses do more than sharpen your vision. They sit comfortably, balance your features and support the way you work, travel and spend time outdoors. Start with fit, then refine the shape, material and lens options.",
      fontSize: "large",
    },
    {
      id: "sample-h2-face",
      type: "heading2",
      text: "1. Begin with your face shape",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-face-copy",
      type: "paragraph",
      text: "Contrast usually creates balance. Angular rectangular frames can add definition to round faces, while round or softly curved frames can complement square jawlines. Oval faces suit many silhouettes, but the frame should still be proportionate to the width of the face.",
      fontSize: "normal",
    },
    {
      id: "sample-quote",
      type: "quote",
      text: "A flattering frame starts with correct measurements. Style works best when the bridge, lens width and temples already fit.",
      italic: true,
      fontSize: "large",
    },
    {
      id: "sample-inline-image",
      type: "image",
      text: "",
      image: "/about-glasses-tortoise.jpg",
      alt: "Tortoiseshell acetate eyeglasses showing frame shape and bridge design",
      fontSize: "normal",
    },
    {
      id: "sample-h2-size",
      type: "heading2",
      text: "2. Check the three essential measurements",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-h3-lens",
      type: "heading3",
      text: "Lens width",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-lens-copy",
      type: "paragraph",
      text: "Lens width controls the overall scale of the frame. A frame that is too wide can slide and make the eyes look off-centre; one that is too narrow may press at the temples.",
      fontSize: "normal",
    },
    {
      id: "sample-h3-bridge",
      type: "heading3",
      text: "Bridge and temple length",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-bridge-copy",
      type: "paragraph",
      text: "The bridge should distribute weight without pinching or slipping. Temple arms should reach behind the ears without bowing outward. Compare the numbers printed inside a comfortable existing frame before ordering.",
      fontSize: "normal",
    },
    {
      id: "sample-h2-lifestyle",
      type: "heading2",
      text: "3. Match the material to your routine",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-material-copy",
      type: "paragraph",
      text: "Acetate offers rich colour and a substantial feel. Titanium is light, corrosion resistant and ideal for long wear. Flexible performance materials suit active routines and children's eyewear. Your prescription also matters because stronger lenses may benefit from smaller, well-centred frame shapes.",
      fontSize: "normal",
    },
    {
      id: "sample-h2-lenses",
      type: "heading2",
      text: "4. Choose lenses for how you actually use your eyes",
      bold: true,
      fontSize: "normal",
    },
    {
      id: "sample-lenses-copy",
      type: "paragraph",
      text: "Discuss screen time, driving, outdoor exposure and reading distance with your optician. Anti-reflective coatings improve clarity, photochromic lenses adapt to changing light, and properly fitted progressive lenses support multiple viewing distances.",
      fontSize: "normal",
    },
    {
      id: "sample-final",
      type: "paragraph",
      text: "When in doubt, send Nigah your current frame measurements and prescription. Our team can shortlist shapes that fit correctly before you decide on colour and finish.",
      bold: true,
      fontSize: "normal",
    },
  ],
};
