import heroOne from "@/assets/hero-1.jpg";
import heroTwo from "@/assets/hero-2.jpg";
import heroThree from "@/assets/hero-3.jpg";
import bannerGlasses from "@/assets/banner-glasses.jpg";
import bannerLenses from "@/assets/banner-lenses.jpg";
import pAviatorBlack from "@/assets/p-aviator-black.jpg";
import pAviatorBlue from "@/assets/p-aviator-blue.jpg";
import pRound from "@/assets/p-round-tortoise.jpg";
import pTitanium from "@/assets/p-titanium.jpg";
import pDaily from "@/assets/p-daily-lens.jpg";
import pColor from "@/assets/p-color-lens.jpg";
import pMonthly from "@/assets/p-monthly-lens.jpg";

import catGlasses from "@/assets/cat-mens.jpg";
import catLenses from "@/assets/cat-lenses.jpg";

import type {
  AnnouncementSettings,
  Brand,
  Category,
  Collection,
  HeroSlide,
  Order,
  Product,
  SocialReel,
  StoreSettings,
  Testimonial,
  VideoSettings,
  FAQItem,
  Subscriber,
  EmailCampaign,
} from "./types";

export const seedCategories: Category[] = [
  {
    id: "cat-glasses",
    slug: "glasses",
    name: "Glasses",
    image: catGlasses,
    banner: {
      image: bannerGlasses,
      heading: "Intelligent Eyewear Collection",
      subtext: "Screen protection • Transition tint • Drive-safe clarity",
      ctaText: "Shop Glasses",
      ctaLink: "/glasses",
    },
  },
  {
    id: "cat-lenses",
    slug: "lenses",
    name: "Lenses",
    image: catLenses,
    banner: {
      image: bannerLenses,
      heading: "Contact Lenses, Perfected",
      subtext: "Daily comfort, breathable hydration, optician-approved",
      ctaText: "Explore Lenses",
      ctaLink: "/lenses",
    },
  },
];

export const seedCollections: Collection[] = [
  {
    id: "col-sunglasses",
    categoryId: "cat-glasses",
    slug: "sunglasses",
    name: "Sunglasses",
    showInNav: true,
    sortOrder: 1,
    banner: {
      image: bannerGlasses,
      heading: "Architectural Sunglasses",
      subtext: "100% UV400 Polarized Protection • Italian Acetate",
      ctaText: "Explore Sunglasses",
      ctaLink: "/glasses",
    },
  },
  {
    id: "col-kids-glasses",
    categoryId: "cat-glasses",
    slug: "kids-glasses",
    name: "Kids Glasses",
    showInNav: true,
    sortOrder: 2,
    banner: {
      image: bannerGlasses,
      heading: "Resilient Frames for Young Vision",
      subtext: "Super-flexible hinge tech • Impact resistant polycarbonate",
      ctaText: "Explore Kids",
      ctaLink: "/glasses",
    },
  },
  {
    id: "col-unisex-glasses",
    categoryId: "cat-glasses",
    slug: "unisex-glasses",
    name: "Unisex Glasses",
    showInNav: true,
    sortOrder: 3,
    banner: {
      image: bannerGlasses,
      heading: "Essential Minimalist Silhouettes",
      subtext: "Engineered in featherweight titanium and timeless finishes",
      ctaText: "Explore Unisex",
      ctaLink: "/glasses",
    },
  },
  {
    id: "col-daily-lenses",
    categoryId: "cat-lenses",
    slug: "daily-lenses",
    name: "Daily Lenses",
    showInNav: true,
    sortOrder: 1,
    banner: {
      image: bannerLenses,
      heading: "Daily Breathable Hydrogel",
      subtext: "Fresh hydration pair every single morning",
      ctaText: "Explore Daily",
      ctaLink: "/lenses",
    },
  },
  {
    id: "col-colored-lenses",
    categoryId: "cat-lenses",
    slug: "colored-lenses",
    name: "Colored Lenses",
    showInNav: true,
    sortOrder: 2,
    banner: {
      image: bannerLenses,
      heading: "Natural Subtle Iris Tones",
      subtext: "Multi-tone natural gradation with high oxygen permeability",
      ctaText: "Explore Colors",
      ctaLink: "/lenses",
    },
  },
  {
    id: "col-monthly-lenses",
    categoryId: "cat-lenses",
    slug: "monthly-lenses",
    name: "Monthly Toric Lenses",
    showInNav: true,
    sortOrder: 3,
    banner: {
      image: bannerLenses,
      heading: "Precision Astigmatism Correction",
      subtext: "Prism-stabilized optical design with monthly value packs",
      ctaText: "Explore Monthly",
      ctaLink: "/lenses",
    },
  },
];

export const seedProducts: Product[] = [
  {
    id: "prd-aviator",
    slug: "classic-aviator",
    name: "Classic Aviator",
    categoryId: "cat-glasses",
    collectionId: "col-sunglasses",
    price: 8900,
    salePrice: 7999,
    sku: "OPT-AV-890",
    status: "Published",
    description:
      "An enduring double-bridge silhouette rebuilt in hand-polished acetate with adjustable titanium temples. Balanced weight distribution keeps it comfortable through long working days.",
    image: pAviatorBlack,
    hoverImage: pAviatorBlue,
    subImages: [pAviatorBlue, pRound],
    stock: 0,
    variants: [
      { id: "var-aviator-black", label: "Jet Black", swatchColourHex: "#141416", image: pAviatorBlack, stock: 12, price: 8900 },
      { id: "var-aviator-blue", label: "Sapphire Blue", swatchColourHex: "#1e3a8a", image: pAviatorBlue, stock: 3, price: 9200 },
    ],
    details: {
      frameMaterial: "Acetate",
      lensMaterial: "Polycarbonate",
      lensType: ["Single Vision", "Polarized", "Blue Light"],
      uvProtection: "UV400",
      warranty: "1 Year Official Optique Guarantee",
      material: "Hand-polished Italian acetate front, beta-titanium temples.",
      lensInfo: "Compatible with single vision, progressive and blue-light filters.",
      care: "Rinse with lukewarm water, dry with the supplied microfibre cloth.",
    },
    featured: true,
    isBestseller: true,
    isNewArrival: false,
    createdAt: "2026-06-02T10:00:00.000Z",
  },
  {
    id: "prd-round",
    slug: "atelier-round",
    name: "Atelier Round",
    categoryId: "cat-glasses",
    collectionId: "col-unisex-glasses",
    price: 7400,
    salePrice: null,
    sku: "OPT-AR-740",
    status: "Published",
    description:
      "A softly rounded tortoiseshell frame with a slim keyhole bridge — a quiet, intellectual shape that flatters most face widths.",
    image: pRound,
    hoverImage: pTitanium,
    subImages: [pTitanium],
    stock: 9,
    variants: [
      { id: "var-round-tortoise", label: "Havana Tortoise", swatchColourHex: "#78350f", image: pRound, stock: 9 },
    ],
    details: {
      frameMaterial: "Acetate",
      lensMaterial: "Glass",
      lensType: ["Single Vision", "Progressive"],
      uvProtection: "UV400",
      warranty: "1 Year Manufacturer Warranty",
      material: "Layered tortoiseshell acetate with stainless steel core wire.",
      lensInfo: "Best suited to prescriptions up to -4.00 for edge-thin lenses.",
      care: "Store in the hard case; avoid leaving in direct sunlight.",
    },
    featured: true,
    isBestseller: true,
    createdAt: "2026-05-18T10:00:00.000Z",
  },
  {
    id: "prd-titanium",
    slug: "meridian-titanium",
    name: "Meridian Titanium",
    categoryId: "cat-glasses",
    collectionId: "col-unisex-glasses",
    price: 12500,
    salePrice: 11200,
    sku: "OPT-MT-125",
    status: "Published",
    description:
      "Featherweight rimless engineering at 11 grams. Precision-milled titanium with screwless hinges for a frame you forget you are wearing.",
    image: pTitanium,
    hoverImage: pRound,
    subImages: [],
    stock: 4,
    variants: [
      { id: "var-titanium-silver", label: "Brushed Silver", swatchColourHex: "#94a3b8", image: pTitanium, stock: 4 },
    ],
    details: {
      frameMaterial: "Titanium",
      lensMaterial: "Trivex",
      lensType: ["Progressive", "Blue Light", "Photochromic"],
      uvProtection: "Polarized+UV",
      warranty: "2 Years Premium Warranty",
      material: "Grade-5 titanium, hypoallergenic nose pads.",
      lensInfo: "Requires drill-mount lenses — fitted in our workshop.",
      care: "Tighten mounts annually at any OPTIQUE counter, free of charge.",
    },
    featured: true,
    isBestseller: true,
    createdAt: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "prd-wayfarer-demo",
    slug: "optique-wayfarer-pro",
    name: "Optique Wayfarer Pro",
    categoryId: "cat-glasses",
    collectionId: "col-sunglasses",
    price: 9800,
    salePrice: 8800,
    sku: "OPT-WF-980",
    status: "Published",
    description:
      "A modern reinterpretation of the iconic wayfarer silhouette — hand-finished in premium Italian acetate with spring-loaded titanium hinges. Three bold colourways, all optician-fitted in store.",
    image: pAviatorBlack,
    hoverImage: pTitanium,
    subImages: [pAviatorBlue, pRound, pTitanium],
    stock: 0,
    variants: [
      { id: "var-way-black", label: "Matte Black", swatchColourHex: "#1a1a1a", image: pAviatorBlack, stock: 8, price: 9800 },
      { id: "var-way-tortoise", label: "Amber Tortoise", swatchColourHex: "#92400e", image: pRound, stock: 5, price: 9800 },
      { id: "var-way-blue", label: "Midnight Navy", swatchColourHex: "#1e40af", image: pAviatorBlue, stock: 2, price: 10200 },
    ],
    details: {
      frameMaterial: "Acetate",
      lensMaterial: "Polycarbonate",
      lensType: ["Single Vision", "Polarized", "Photochromic"],
      uvProtection: "Polarized+UV",
      warranty: "2 Years Comprehensive Frame Warranty",
      material: "Italian bio-acetate front with grade-5 titanium spring hinges. Hypoallergenic nose pads.",
      lensInfo: "Fits single-vision, progressive and blue-light filter lenses up to +/- 6.00.",
      care: "Clean with the supplied microfibre cloth. Store in the hard case when not in use. Avoid extreme heat.",
    },
    featured: true,
    isNewArrival: true,
    newArrivalImage: pAviatorBlack,
    isBestseller: true,
    createdAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "prd-kids-flex",
    slug: "junior-flex-square",
    name: "Junior Flex Square",
    categoryId: "cat-glasses",
    collectionId: "col-kids-glasses",
    price: 5400,
    salePrice: 4799,
    sku: "OPT-KF-540",
    status: "Published",
    description:
      "Engineered specifically for active youngsters. Twistable, unbreakable silicone temples with soft-touch bridge cushioning.",
    image: pRound,
    hoverImage: pAviatorBlue,
    subImages: [pAviatorBlue],
    stock: 15,
    variants: [
      { id: "var-kids-blue", label: "Electric Blue", swatchColourHex: "#2563eb", image: pAviatorBlue, stock: 10 },
      { id: "var-kids-amber", label: "Warm Amber", swatchColourHex: "#d97706", image: pRound, stock: 5 },
    ],
    details: {
      frameMaterial: "Plastic",
      lensMaterial: "Polycarbonate",
      lensType: ["Single Vision", "Blue Light"],
      uvProtection: "UV400",
      warranty: "1 Year Accidental Breakage Guarantee",
      material: "BPA-free medical grade elastomer & shatterproof hinges.",
      lensInfo: "Child-safe impact resistant CR-39 and polycarbonate lenses.",
      care: "Wash with mild soap and room temperature water.",
    },
    featured: true,
    isNewArrival: true,
    newArrivalImage: pRound,
    createdAt: "2026-08-15T10:00:00.000Z",
  },
  {
    id: "prd-daily",
    slug: "clarity-daily-lenses",
    name: "Clarity Daily Lenses",
    categoryId: "cat-lenses",
    collectionId: "col-daily-lenses",
    price: 3200,
    salePrice: null,
    sku: "OPT-DL-320",
    status: "Published",
    description:
      "A 30-pack of ultra-thin daily disposables with a 58% water content — fresh optics every morning, nothing to clean at night.",
    image: pDaily,
    hoverImage: pMonthly,
    subImages: [pMonthly],
    stock: 26,
    variants: [],
    details: {
      lensMaterial: "Hydrogel",
      lensType: ["Single Vision"],
      uvProtection: "UV400",
      warranty: "Fresh Batch Guaranteed",
      material: "Hydrogel with UV-A / UV-B blocking.",
      lensInfo: "Powers from -0.50 to -8.00 in 0.25 steps.",
      care: "Single use only — never re-wear a daily lens.",
    },
    featured: true,
    isBestseller: true,
    createdAt: "2026-06-11T10:00:00.000Z",
  },
  {
    id: "prd-color",
    slug: "hazel-tone-lenses",
    name: "Hazel Tone Lenses",
    categoryId: "cat-lenses",
    collectionId: "col-colored-lenses",
    price: 4100,
    salePrice: 3699,
    sku: "OPT-CL-410",
    status: "Published",
    description:
      "Naturally graded colour lenses with a soft limbal ring, designed to warm the iris without looking printed.",
    image: pColor,
    hoverImage: pDaily,
    subImages: [],
    stock: 2,
    variants: [
      { id: "var-color-hazel", label: "Warm Hazel", swatchColourHex: "#b45309", image: pColor, stock: 2 },
    ],
    details: {
      lensMaterial: "Silicone hydrogel",
      lensType: ["Single Vision"],
      uvProtection: "UV400",
      warranty: "Sterility sealed guarantee",
      material: "Silicone hydrogel with three-tone pigment sandwich.",
      lensInfo: "Available plano and in powers to -6.00.",
      care: "Disinfect nightly in fresh multi-purpose solution.",
    },
    featured: false,
    createdAt: "2026-04-29T10:00:00.000Z",
  },
  {
    id: "prd-monthly",
    slug: "monthly-toric-lenses",
    name: "Monthly Toric Lenses",
    categoryId: "cat-lenses",
    collectionId: "col-monthly-lenses",
    price: 5600,
    salePrice: null,
    sku: "OPT-TL-560",
    status: "Published",
    description:
      "Stabilised toric lenses for astigmatism, bundled with a 120ml care solution and travel case.",
    image: pMonthly,
    hoverImage: pDaily,
    subImages: [pDaily],
    stock: 0,
    variants: [],
    details: {
      lensMaterial: "Silicone hydrogel",
      lensType: ["Single Vision"],
      uvProtection: "UV400",
      warranty: "Manufacturer Authenticity Seal",
      material: "Silicone hydrogel, 6-month blister shelf life.",
      lensInfo: "Cylinder -0.75 to -2.25, axis fitted after an in-store check.",
      care: "Replace the case every three months.",
    },
    featured: false,
    createdAt: "2026-03-14T10:00:00.000Z",
  },
  {
    id: "prd-aqua-lens-demo",
    slug: "aqua-comfort-monthly",
    name: "Aqua Comfort Monthly",
    categoryId: "cat-lenses",
    collectionId: "col-monthly-lenses",
    price: 4800,
    salePrice: 4299,
    sku: "OPT-AQ-480",
    status: "Published",
    description:
      "Extended-wear monthly lenses with a 62% water content silicone hydrogel. Ideal for long screen hours — moisture-lock technology keeps eyes fresh from morning to night.",
    image: pMonthly,
    subImages: [pDaily, pColor],
    stock: 35,
    variants: [],
    details: {
      lensMaterial: "Silicone hydrogel",
      lensType: ["Single Vision"],
      uvProtection: "UV400",
      warranty: "100% Fit Comfort Guarantee",
      material: "Silicone hydrogel with moisture-lock polymer coating. UV-A and UV-B blocking built in.",
      lensInfo: "Powers -0.25 to -10.00 and +0.25 to +4.00. Cylinder and axis available for toric version.",
      care: "Use fresh multipurpose solution nightly. Replace lens case every 3 months. Never rinse with tap water.",
    },
    featured: true,
    isNewArrival: true,
    newArrivalImage: pMonthly,
    createdAt: "2026-09-02T10:00:00.000Z",
  },
];

export const seedOrders: Order[] = [
  {
    id: "ord-1001",
    reference: "OPT-204118",
    createdAt: "2026-08-22T09:12:00.000Z",
    customerName: "Ayesha Khan",
    contact: "+92 300 1234567",
    productId: "prd-aviator",
    productName: "Classic Aviator",
    variantId: "var-aviator-black",
    variantLabel: "Black",
    message: "Is the black frame available for pickup this week?",
    source: "whatsapp",
    status: "New",
    stockDeducted: false,
  },
  {
    id: "ord-1002",
    reference: "OPT-198744",
    createdAt: "2026-08-20T15:40:00.000Z",
    customerName: "Bilal Ahmed",
    contact: "bilal.ahmed@example.com",
    productId: "prd-daily",
    productName: "Clarity Daily Lenses",
    variantId: null,
    variantLabel: null,
    message: "Need two boxes at -2.25. Do you deliver to Lahore?",
    source: "form",
    status: "Contacted",
    stockDeducted: false,
  },
  {
    id: "ord-1003",
    reference: "OPT-186320",
    createdAt: "2026-08-17T11:05:00.000Z",
    customerName: "Sana Yousuf",
    contact: "+92 321 9876543",
    productId: "prd-titanium",
    productName: "Meridian Titanium",
    variantId: null,
    variantLabel: null,
    message: "Ordered on WhatsApp — collected in store.",
    source: "whatsapp",
    status: "Completed",
    stockDeducted: true,
  },
  {
    id: "ord-1004",
    reference: "OPT-175509",
    createdAt: "2026-08-12T18:22:00.000Z",
    customerName: "Hamza Iqbal",
    contact: "hamza@example.com",
    productId: "prd-color",
    productName: "Hazel Tone Lenses",
    variantId: null,
    variantLabel: null,
    message: "Changed my mind, please cancel.",
    source: "form",
    status: "Cancelled",
    stockDeducted: false,
  },
];

export const seedHeroSlides: HeroSlide[] = [
  {
    id: "hero-1",
    image: heroOne,
    eyebrow: "New Season Optics",
    headline: "Frames cut for the way you actually see",
    subtext: "Hand-finished acetate and titanium, fitted by opticians in-store.",
    ctaText: "Shop Frames",
    ctaLink: "/glasses",
    enabled: true,
  },
  {
    id: "hero-2",
    image: heroTwo,
    eyebrow: "Precision Fitting",
    headline: "A lens is only as good as its fit",
    subtext: "Free measurement and adjustment for the life of your frame.",
    ctaText: "Book a Fitting",
    ctaLink: "/contact",
    enabled: true,
  },
  {
    id: "hero-3",
    image: heroThree,
    eyebrow: "Daily Comfort",
    headline: "Contact lenses that breathe all day",
    subtext: "Hydrogel dailies, torics and colour tones — all optician approved.",
    ctaText: "Explore Lenses",
    ctaLink: "/lenses",
    enabled: true,
  },
];

export const seedAnnouncement: AnnouncementSettings = {
  enabled: true,
  messages: [
    "Back in stock: the Classic Aviator",
    "New drop: Blue Light lenses now available",
    "Free delivery on orders above Rs. 5,000",
    "Visit our warehouse showroom",
  ],
  background: "#0E0E10",
  textColor: "#F6F4EF",
};

export const seedTestimonials: Testimonial[] = [
  {
    id: "tst-1",
    name: "Kristin Watson",
    email: "kristin.w@gmail.com",
    productId: "prd-aviator",
    productName: "Classic Aviator",
    title: "Love It: My Recent Eyewear Purchase",
    quote:
      "I recently picked up these aviator frames and I have to say, I'm loving them! From the fit to the finish, everything about these is just perfect. Super comfortable and stylish.",
    rating: 5,
    verified: true,
    createdAt: "2026-08-10T14:20:00.000Z",
    photo: null,
    reviewImage: pAviatorBlack,
  },
  {
    id: "tst-2",
    name: "Bessie Cooper",
    email: "bessie.cooper@yahoo.com",
    productId: "prd-aviator",
    productName: "Classic Aviator",
    title: "Excellent Product, I like it!",
    quote:
      "The fitting appointment was worth the trip alone. My progressives finally feel natural instead of like a compromise. Frame weight is balanced wonderfully.",
    rating: 5,
    verified: true,
    createdAt: "2026-07-28T10:15:00.000Z",
    photo: null,
    reviewImage: heroTwo,
  },
  {
    id: "tst-3",
    name: "Usman Tariq",
    email: "usman.tariq@hotmail.com",
    productId: "prd-titanium",
    productName: "Meridian Titanium",
    title: "Featherweight & Fast Delivery",
    quote:
      "Ordered the Meridian Titanium on WhatsApp at 9pm and had it adjusted on my face the next afternoon. Extremely light weight!",
    rating: 5,
    verified: true,
    createdAt: "2026-08-15T09:30:00.000Z",
    photo: null,
    reviewImage: pAviatorBlue,
  },
  {
    id: "tst-4",
    name: "Zainab Ali",
    email: "zainab.ali@outlook.com",
    productId: "prd-daily",
    productName: "Clarity Daily Lenses",
    title: "Optician Approved Hydration",
    quote:
      "I've bought lenses online for years — this is the first time someone actually checked my prescription first. Very breathable daily lenses.",
    rating: 4,
    verified: true,
    createdAt: "2026-08-20T16:45:00.000Z",
    photo: null,
    reviewImage: heroThree,
  },
  {
    id: "tst-5",
    name: "Hamza Sheikh",
    email: "hamza.s@gmail.com",
    productId: "prd-round",
    productName: "Atelier Round",
    title: "Frame sizing was slightly snug",
    quote:
      "The tortoiseshell pattern looks premium, but the frame bridge is a bit narrow for wide face shapes. Good optical clarity though.",
    rating: 3,
    verified: false,
    createdAt: "2026-08-05T11:10:00.000Z",
    photo: null,
    reviewImage: pRound,
  },
  {
    id: "tst-6",
    name: "Faisal Rehman",
    email: "faisal.rehman@gmail.com",
    productId: "prd-wayfarer-demo",
    productName: "Optique Wayfarer Pro",
    title: "Quiet showroom, genuine staff",
    quote: "Quiet showroom, no pressure, genuinely knowledgeable staff. The wayfarer frames speak for themselves.",
    rating: 5,
    verified: true,
    createdAt: "2026-08-25T18:00:00.000Z",
    photo: null,
    reviewImage: null,
  },
];

export const seedVideo: VideoSettings = {
  lockedChannel: "",
  videoUrl: "",
  videoId: null,
  caption: "A look inside the workshop where every OPTIQUE frame is finished and quality-checked by hand.",
};

export const seedSettings: StoreSettings = {
  storeName: "OPTIQUE",
  logo: null,
  whatsapp: "+923001234567",
  email: "hello@optique.example",
  phone: "+92 300 1234567",
  address: "24 Lens Court, Clifton Block 4, Karachi",
  hours: "Mon–Sat, 11:00 – 20:00",
  lowStockThreshold: 5,
  adminEmail: "admin@optique.com",
  adminPassword: "optique123",
  aboutHeadline: "Optics, made deliberately slow",
  aboutBody:
    "OPTIQUE began in a single workshop with one belief: a pair of glasses is a medical instrument you happen to wear on your face. Every frame we sell is chosen for how it holds a lens, not just how it photographs.\n\nWe cut, polish and fit in-house. Our opticians measure each pupil individually, adjust the bridge to your nose, and keep your file so a repair years later still fits like the first day.\n\nWe stock only what we would wear ourselves — a short, considered range of frames and lenses backed by a full warranty and honest advice.",
};

export const seedBrands: Brand[] = [
  { id: "brd-1", name: "Ray-Ban", logo: null, enabled: true },
  { id: "brd-2", name: "Oakley", logo: null, enabled: true },
  { id: "brd-3", name: "Tommy Hilfiger", logo: null, enabled: true },
  { id: "brd-4", name: "Superdry", logo: null, enabled: true },
  { id: "brd-5", name: "DKNY", logo: null, enabled: true },
  { id: "brd-6", name: "Versace", logo: null, enabled: true },
];

export const seedSocialReels: SocialReel[] = [
  {
    id: "reel-1",
    title: "Unboxing the Classic Aviators in Jet Black",
    creatorName: "Hamza Malik",
    creatorHandle: "@hamza.style",
    platform: "instagram",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: heroOne,
    duration: "00:39",
    productId: "prd-aviator",
    enabled: true,
  },
  {
    id: "reel-2",
    title: "Reading & Screen Comfort with Blue Light Lenses",
    creatorName: "Ayesha Tariq",
    creatorHandle: "@ayesha.reads",
    platform: "tiktok",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: heroTwo,
    duration: "00:34",
    productId: "prd-round",
    enabled: true,
  },
  {
    id: "reel-3",
    title: "My daily eyewear styling routine with Optique frames",
    creatorName: "Zainab Khan",
    creatorHandle: "@zainab.glam",
    platform: "instagram",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: heroThree,
    duration: "00:38",
    productId: "prd-titanium",
    enabled: true,
  },
  {
    id: "reel-4",
    title: "Why these contact lenses are a total game changer",
    creatorName: "Nimra Ali",
    creatorHandle: "@nimra_vlogs",
    platform: "youtube",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: catGlasses,
    duration: "00:57",
    productId: "prd-daily",
    enabled: true,
  },
  {
    id: "reel-5",
    title: "Optique Wayfarer Pro — Italian Acetate & Titanium Spring Hinges",
    creatorName: "Faisal Rehman",
    creatorHandle: "@faisal.optics",
    platform: "instagram",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: pAviatorBlack,
    duration: "00:45",
    productId: "prd-wayfarer-demo",
    enabled: true,
  },
  {
    id: "reel-6",
    title: "Testing polarising clarity on the Wayfarer Pro",
    creatorName: "Usman Tariq",
    creatorHandle: "@usman_reviews",
    platform: "tiktok",
    videoUrl: "https://www.youtube.com/shorts/dQw4w9WgXcQ",
    thumbnail: pAviatorBlue,
    duration: "00:30",
    productId: "prd-wayfarer-demo",
    enabled: true,
  },
];

export const seedBrandsRemaining: Brand[] = [
  { id: "brd-7", name: "Gucci", logo: null, enabled: true },
  { id: "brd-8", name: "Prada", logo: null, enabled: true },
];

export const seedFaqs: FAQItem[] = [
  {
    id: "faq-1",
    question: "How do I submit my prescription for eyeglasses?",
    answer:
      "You can easily upload a photo or scan of your prescription during checkout or send it directly to our WhatsApp optician helpline (+92 300 1234567). Our qualified optical team verifies every single parameter (SPH, CYL, Axis, and Pupillary Distance) before custom crafting your lenses in our workshop.",
    category: "Prescription & Lenses",
    enabled: true,
  },
  {
    id: "faq-2",
    question: "What lens coatings and optical types do you offer?",
    answer:
      "We provide premium Single Vision, Digital Progressive (bifocal/multifocal), Blue Light Blocking (designed to reduce screen fatigue), Light-Responsive Photochromic (transitions), and 100% Polarized UV400 Sun Lenses. Every pair includes multi-layer anti-reflective and hydrophobic scratch-resistant coatings at no extra charge.",
    category: "Prescription & Lenses",
    enabled: true,
  },
  {
    id: "faq-3",
    question: "How long does shipping take across Pakistan?",
    answer:
      "Non-prescription frames and standard contact lenses are dispatched within 24 hours. Custom prescription glasses are carefully cut, edged, and laser-aligned in our workshop, taking 3-5 business days to reach your doorstep nationwide via insured priority courier.",
    category: "Orders & Delivery",
    enabled: true,
  },
  {
    id: "faq-4",
    question: "Can I try frames in person or get a physical fitting?",
    answer:
      "Yes! You are warmly invited to visit our boutique showroom at Clifton Block 4, Karachi for a personalized optician fitting. If you order online and require fit adjustments, you can visit us anytime or have any reputable optician fine-tune the temple curve free of charge.",
    category: "Fitting & Showroom",
    enabled: true,
  },
  {
    id: "faq-5",
    question: "What is your return and warranty guarantee?",
    answer:
      "Every frame is backed by our official 1-Year OPTIQUE Manufacturer Warranty covering screwless hinges and structural integrity. If you're not completely satisfied with how a frame feels on your face, we provide an easy 7-day hassle-free return and exchange policy.",
    category: "Warranty & Returns",
    enabled: true,
  },
  {
    id: "faq-6",
    question: "How do I know which frame size suits my face shape?",
    answer:
      "Every product page displays the exact frame measurements (Lens Width, Bridge Width, and Temple Arm Length). You can compare these with your current comfortable glasses. You can also send your photo to our WhatsApp stylist for personalized face-shape recommendations.",
    category: "Fitting & Showroom",
    enabled: true,
  },
];

export const seedSubscribers: Subscriber[] = [
  {
    id: "sub-1",
    email: "sarah.khan@example.com",
    createdAt: "2026-08-20T14:30:00.000Z",
    status: "active",
  },
  {
    id: "sub-2",
    email: "ali.reza@example.com",
    createdAt: "2026-08-24T09:15:00.000Z",
    status: "active",
  },
  {
    id: "sub-3",
    email: "fatima.noor@example.com",
    createdAt: "2026-08-28T18:45:00.000Z",
    status: "active",
  },
  {
    id: "sub-4",
    email: "usman.optical@example.com",
    createdAt: "2026-09-01T11:20:00.000Z",
    status: "active",
  },
];

export const seedCampaigns: EmailCampaign[] = [
  {
    id: "cmp-1",
    subject: "✨ Exclusive 20% Off: New Handcrafted Titanium Arrivals",
    headline: "Autumn Optical Collection is Live",
    bodyText:
      "Explore our newest drop of ultra-light Japanese titanium and Mazzucchelli acetate frames. Designed for all-day comfort and fitted with precision blue-light or prescription lenses.",
    bannerImage: heroOne,
    promoCode: "OPTIQUE20",
    ctaText: "Explore New Frames",
    ctaLink: "/glasses",
    sentAt: "2026-09-01T12:00:00.000Z",
    recipientCount: 4,
  },
];
