/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FrameSizeGuideRouteImport } from './routes/frame-size-guide'
import { Route as GlassesRouteImport } from './routes/glasses'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LensGuideRouteImport } from './routes/lens-guide'
import { Route as LensesRouteImport } from './routes/lenses'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as OrderStatusRouteImport } from './routes/order-status'
import { Route as PrescriptionGuideRouteImport } from './routes/prescription-guide'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminQueriesRouteImport } from './routes/admin.queries'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiV1OrdersRouteImport } from './routes/api.v1.orders'
import { Route as ApiV1AdminCredentialsRouteImport } from './routes/api.v1.admin.credentials'
import { Route as ApiV1AdminLoginRouteImport } from './routes/api.v1.admin.login'
import { Route as ApiV1AdminRecoverRouteImport } from './routes/api.v1.admin.recover'
import { Route as ApiV1AdminSignupRouteImport } from './routes/api.v1.admin.signup'
import { Route as ApiV1AdminStatusRouteImport } from './routes/api.v1.admin.status'
import { Route as ApiV1MetaEventsRouteImport } from './routes/api.v1.meta.events'
import { Route as ApiV1OrdersIdRouteImport } from './routes/api.v1.orders.$id'
import { Route as ApiV1OrdersTrackReferenceRouteImport } from './routes/api.v1.orders.track.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameSizeGuideRoute = FrameSizeGuideRouteImport.update({
  id: '/frame-size-guide',
  path: '/frame-size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GlassesRoute = GlassesRouteImport.update({
  id: '/glasses',
  path: '/glasses',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LensGuideRoute = LensGuideRouteImport.update({
  id: '/lens-guide',
  path: '/lens-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LensesRoute = LensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionGuideRoute = PrescriptionGuideRouteImport.update({
  id: '/prescription-guide',
  path: '/prescription-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueriesRoute = AdminQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersRoute = ApiV1OrdersRouteImport.update({
  id: '/api/v1/orders',
  path: '/api/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminCredentialsRoute = ApiV1AdminCredentialsRouteImport.update({
  id: '/api/v1/admin/credentials',
  path: '/api/v1/admin/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminLoginRoute = ApiV1AdminLoginRouteImport.update({
  id: '/api/v1/admin/login',
  path: '/api/v1/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminRecoverRoute = ApiV1AdminRecoverRouteImport.update({
  id: '/api/v1/admin/recover',
  path: '/api/v1/admin/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminSignupRoute = ApiV1AdminSignupRouteImport.update({
  id: '/api/v1/admin/signup',
  path: '/api/v1/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminStatusRoute = ApiV1AdminStatusRouteImport.update({
  id: '/api/v1/admin/status',
  path: '/api/v1/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetaEventsRoute = ApiV1MetaEventsRouteImport.update({
  id: '/api/v1/meta/events',
  path: '/api/v1/meta/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OrdersIdRoute = ApiV1OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1OrdersRoute,
} as any)
const ApiV1OrdersTrackReferenceRoute =
  ApiV1OrdersTrackReferenceRouteImport.update({
    id: '/track/$reference',
    path: '/track/$reference',
    getParentRoute: () => ApiV1OrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/frame-size-guide': typeof FrameSizeGuideRoute
  '/glasses': typeof GlassesRoute
  '/health': typeof HealthRoute
  '/lens-guide': typeof LensGuideRoute
  '/lenses': typeof LensesRoute
  '/not-found': typeof NotFoundRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-status': typeof OrderStatusRoute
  '/prescription-guide': typeof PrescriptionGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/warranty': typeof WarrantyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/v1/orders': typeof ApiV1OrdersRouteWithChildren
  '/api/v1/admin/credentials': typeof ApiV1AdminCredentialsRoute
  '/api/v1/admin/login': typeof ApiV1AdminLoginRoute
  '/api/v1/admin/recover': typeof ApiV1AdminRecoverRoute
  '/api/v1/admin/signup': typeof ApiV1AdminSignupRoute
  '/api/v1/admin/status': typeof ApiV1AdminStatusRoute
  '/api/v1/meta/events': typeof ApiV1MetaEventsRoute
  '/api/v1/orders/$id': typeof ApiV1OrdersIdRoute
  '/api/v1/orders/track/$reference': typeof ApiV1OrdersTrackReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/frame-size-guide': typeof FrameSizeGuideRoute
  '/glasses': typeof GlassesRoute
  '/health': typeof HealthRoute
  '/lens-guide': typeof LensGuideRoute
  '/lenses': typeof LensesRoute
  '/not-found': typeof NotFoundRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-status': typeof OrderStatusRoute
  '/prescription-guide': typeof PrescriptionGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/warranty': typeof WarrantyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/v1/orders': typeof ApiV1OrdersRouteWithChildren
  '/api/v1/admin/credentials': typeof ApiV1AdminCredentialsRoute
  '/api/v1/admin/login': typeof ApiV1AdminLoginRoute
  '/api/v1/admin/recover': typeof ApiV1AdminRecoverRoute
  '/api/v1/admin/signup': typeof ApiV1AdminSignupRoute
  '/api/v1/admin/status': typeof ApiV1AdminStatusRoute
  '/api/v1/meta/events': typeof ApiV1MetaEventsRoute
  '/api/v1/orders/$id': typeof ApiV1OrdersIdRoute
  '/api/v1/orders/track/$reference': typeof ApiV1OrdersTrackReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/faqs': typeof FaqsRoute
  '/frame-size-guide': typeof FrameSizeGuideRoute
  '/glasses': typeof GlassesRoute
  '/health': typeof HealthRoute
  '/lens-guide': typeof LensGuideRoute
  '/lenses': typeof LensesRoute
  '/not-found': typeof NotFoundRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-status': typeof OrderStatusRoute
  '/prescription-guide': typeof PrescriptionGuideRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/warranty': typeof WarrantyRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/queries': typeof AdminQueriesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/v1/orders': typeof ApiV1OrdersRouteWithChildren
  '/api/v1/admin/credentials': typeof ApiV1AdminCredentialsRoute
  '/api/v1/admin/login': typeof ApiV1AdminLoginRoute
  '/api/v1/admin/recover': typeof ApiV1AdminRecoverRoute
  '/api/v1/admin/signup': typeof ApiV1AdminSignupRoute
  '/api/v1/admin/status': typeof ApiV1AdminStatusRoute
  '/api/v1/meta/events': typeof ApiV1MetaEventsRoute
  '/api/v1/orders/$id': typeof ApiV1OrdersIdRoute
  '/api/v1/orders/track/$reference': typeof ApiV1OrdersTrackReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/faqs'
    | '/frame-size-guide'
    | '/glasses'
    | '/health'
    | '/lens-guide'
    | '/lenses'
    | '/not-found'
    | '/order-confirmation'
    | '/order-status'
    | '/prescription-guide'
    | '/privacy-policy'
    | '/refund-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/warranty'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/faqs'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/queries'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/v1/orders'
    | '/api/v1/admin/credentials'
    | '/api/v1/admin/login'
    | '/api/v1/admin/recover'
    | '/api/v1/admin/signup'
    | '/api/v1/admin/status'
    | '/api/v1/meta/events'
    | '/api/v1/orders/$id'
    | '/api/v1/orders/track/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/faqs'
    | '/frame-size-guide'
    | '/glasses'
    | '/health'
    | '/lens-guide'
    | '/lenses'
    | '/not-found'
    | '/order-confirmation'
    | '/order-status'
    | '/prescription-guide'
    | '/privacy-policy'
    | '/refund-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/warranty'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/faqs'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/queries'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin'
    | '/blog'
    | '/api/v1/orders'
    | '/api/v1/admin/credentials'
    | '/api/v1/admin/login'
    | '/api/v1/admin/recover'
    | '/api/v1/admin/signup'
    | '/api/v1/admin/status'
    | '/api/v1/meta/events'
    | '/api/v1/orders/$id'
    | '/api/v1/orders/track/$reference'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/faqs'
    | '/frame-size-guide'
    | '/glasses'
    | '/health'
    | '/lens-guide'
    | '/lenses'
    | '/not-found'
    | '/order-confirmation'
    | '/order-status'
    | '/prescription-guide'
    | '/privacy-policy'
    | '/refund-policy'
    | '/returns-policy'
    | '/shipping-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/warranty'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/faqs'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/queries'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/v1/orders'
    | '/api/v1/admin/credentials'
    | '/api/v1/admin/login'
    | '/api/v1/admin/recover'
    | '/api/v1/admin/signup'
    | '/api/v1/admin/status'
    | '/api/v1/meta/events'
    | '/api/v1/orders/$id'
    | '/api/v1/orders/track/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FaqsRoute: typeof FaqsRoute
  FrameSizeGuideRoute: typeof FrameSizeGuideRoute
  GlassesRoute: typeof GlassesRoute
  HealthRoute: typeof HealthRoute
  LensGuideRoute: typeof LensGuideRoute
  LensesRoute: typeof LensesRoute
  NotFoundRoute: typeof NotFoundRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrderStatusRoute: typeof OrderStatusRoute
  PrescriptionGuideRoute: typeof PrescriptionGuideRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WarrantyRoute: typeof WarrantyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiV1OrdersRoute: typeof ApiV1OrdersRouteWithChildren
  ApiV1AdminCredentialsRoute: typeof ApiV1AdminCredentialsRoute
  ApiV1AdminLoginRoute: typeof ApiV1AdminLoginRoute
  ApiV1AdminRecoverRoute: typeof ApiV1AdminRecoverRoute
  ApiV1AdminSignupRoute: typeof ApiV1AdminSignupRoute
  ApiV1AdminStatusRoute: typeof ApiV1AdminStatusRoute
  ApiV1MetaEventsRoute: typeof ApiV1MetaEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frame-size-guide': {
      id: '/frame-size-guide'
      path: '/frame-size-guide'
      fullPath: '/frame-size-guide'
      preLoaderRoute: typeof FrameSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glasses': {
      id: '/glasses'
      path: '/glasses'
      fullPath: '/glasses'
      preLoaderRoute: typeof GlassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens-guide': {
      id: '/lens-guide'
      path: '/lens-guide'
      fullPath: '/lens-guide'
      preLoaderRoute: typeof LensGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenses': {
      id: '/lenses'
      path: '/lenses'
      fullPath: '/lenses'
      preLoaderRoute: typeof LensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status': {
      id: '/order-status'
      path: '/order-status'
      fullPath: '/order-status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription-guide': {
      id: '/prescription-guide'
      path: '/prescription-guide'
      fullPath: '/prescription-guide'
      preLoaderRoute: typeof PrescriptionGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queries': {
      id: '/admin/queries'
      path: '/queries'
      fullPath: '/admin/queries'
      preLoaderRoute: typeof AdminQueriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders': {
      id: '/api/v1/orders'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders'
      preLoaderRoute: typeof ApiV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/credentials': {
      id: '/api/v1/admin/credentials'
      path: '/api/v1/admin/credentials'
      fullPath: '/api/v1/admin/credentials'
      preLoaderRoute: typeof ApiV1AdminCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/login': {
      id: '/api/v1/admin/login'
      path: '/api/v1/admin/login'
      fullPath: '/api/v1/admin/login'
      preLoaderRoute: typeof ApiV1AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/recover': {
      id: '/api/v1/admin/recover'
      path: '/api/v1/admin/recover'
      fullPath: '/api/v1/admin/recover'
      preLoaderRoute: typeof ApiV1AdminRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/signup': {
      id: '/api/v1/admin/signup'
      path: '/api/v1/admin/signup'
      fullPath: '/api/v1/admin/signup'
      preLoaderRoute: typeof ApiV1AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/status': {
      id: '/api/v1/admin/status'
      path: '/api/v1/admin/status'
      fullPath: '/api/v1/admin/status'
      preLoaderRoute: typeof ApiV1AdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meta/events': {
      id: '/api/v1/meta/events'
      path: '/api/v1/meta/events'
      fullPath: '/api/v1/meta/events'
      preLoaderRoute: typeof ApiV1MetaEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/orders/$id': {
      id: '/api/v1/orders/$id'
      path: '/$id'
      fullPath: '/api/v1/orders/$id'
      preLoaderRoute: typeof ApiV1OrdersIdRouteImport
      parentRoute: typeof ApiV1OrdersRoute
    }
    '/api/v1/orders/track/$reference': {
      id: '/api/v1/orders/track/$reference'
      path: '/track/$reference'
      fullPath: '/api/v1/orders/track/$reference'
      preLoaderRoute: typeof ApiV1OrdersTrackReferenceRouteImport
      parentRoute: typeof ApiV1OrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQueriesRoute: typeof AdminQueriesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQueriesRoute: AdminQueriesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiV1OrdersRouteChildren {
  ApiV1OrdersIdRoute: typeof ApiV1OrdersIdRoute
  ApiV1OrdersTrackReferenceRoute: typeof ApiV1OrdersTrackReferenceRoute
}

const ApiV1OrdersRouteChildren: ApiV1OrdersRouteChildren = {
  ApiV1OrdersIdRoute: ApiV1OrdersIdRoute,
  ApiV1OrdersTrackReferenceRoute: ApiV1OrdersTrackReferenceRoute,
}

const ApiV1OrdersRouteWithChildren = ApiV1OrdersRoute._addFileChildren(
  ApiV1OrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FaqsRoute: FaqsRoute,
  FrameSizeGuideRoute: FrameSizeGuideRoute,
  GlassesRoute: GlassesRoute,
  HealthRoute: HealthRoute,
  LensGuideRoute: LensGuideRoute,
  LensesRoute: LensesRoute,
  NotFoundRoute: NotFoundRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrderStatusRoute: OrderStatusRoute,
  PrescriptionGuideRoute: PrescriptionGuideRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WarrantyRoute: WarrantyRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiV1OrdersRoute: ApiV1OrdersRouteWithChildren,
  ApiV1AdminCredentialsRoute: ApiV1AdminCredentialsRoute,
  ApiV1AdminLoginRoute: ApiV1AdminLoginRoute,
  ApiV1AdminRecoverRoute: ApiV1AdminRecoverRoute,
  ApiV1AdminSignupRoute: ApiV1AdminSignupRoute,
  ApiV1AdminStatusRoute: ApiV1AdminStatusRoute,
  ApiV1MetaEventsRoute: ApiV1MetaEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
